### ISSUE TITLE
import .xEncode出错

### ISSUE THREAD

**Issue by hechuxun** [Yibo-Li/pytunet#2]
Traceback (most recent call last):
  File "connect.py", line 1, in <module>
    import tunet
  File "/home/pi/codes/pyTunet/pytunet-master/tunet/tunet.py", line 7, in <module>
    from .xEncode import xencode
SystemError: Parent module '' not loaded, cannot perform relative import

将.xEncode改为xEncode可通过

**Comment by Yibo-Li** [comment]
我在windows10+anaconda环境中测试没有报错，请提供发生问题的环境和当时的调用方法
